steps:
  push-tagged-build:
    image: plugins/docker
    settings:
      repo: lblod/besluit-publicatie-publish-service
      tags: "${CI_COMMIT_SHA}"
      purge: true
    secrets: [ docker_username, docker_password ]
when:
  - event: manual
